spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_forum?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0209
  web:
    resources:
      add-mappings: false
server:
  address: 127.0.0.1
  port: 8080